version: "2"
services:
  all-all-aws-connector:
    image: ernestio/all-all-aws-connector:2.0.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      CONNECTORS: nat.create.aws,nat.update.aws,nat.delete.aws,network.create.aws,network.delete.aws,route53.create.aws,route53.delete.aws,route53.update.aws,s3.create.aws,s3.update.aws,s3.delete.aws,elb.create.aws,elb.delete.aws,elb.update.aws,vpc.create.aws,vpc.delete.aws,instance.delete.aws,instance.update.aws,instance.create.aws,firewall.create.aws,firewall.update.aws,firewall.delete.aws,ebs_volume.create.aws,ebs_volume.delete.aws,rds_cluster.create.aws,rds_cluster.update.aws,rds_cluster.delete.aws,rds_instance.create.aws,rds_instance.update.aws,rds_instance.delete.aws,nats.find.aws,networks.find.aws,route53s.find.aws,s3s.find.aws,elbs.find.aws,vpcs.find.aws,instances.find.aws,firewalls.find.aws,ebs_volumes.find.aws,rds_clusters.find.aws,rds_instances.find.aws,internet_gateway.create.aws,internet_gateway.delete.aws,internet_gateways.find.aws
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      NATS_URI: nats://nats:4222
  all-all-fake-connector:
    image: ernestio/all-all-fake-connector:2.0.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      NATS_URI: nats://nats:4222
  all-all-vcloud-connector:
    image: ernestio/all-all-vcloud-connector:2.0.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      NATS_URI: nats://nats:4222
  api-gateway:
    image: ernestio/api-gateway:2.0.0
    ports:
    - 8080:8080
    links:
    - nats
    depends_on:
    - config-store
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      JWT_SECRET: GENERATEDJWTSECRET
      NATS_URI: nats://nats:4222
  config-store:
    image: ernestio/config-store:2.0.0
    entrypoint: /go/bin/config-store -config /etc/ernest/config.json
    volumes:
    - ./config/config-store/:/etc/ernest/
    links:
    - nats
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      NATS_URI: nats://nats:4222
  datacenter-store:
    image: ernestio/datacenter-store:2.0.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      NATS_URI: nats://nats:4222
  definition-mapper:
    image: ernestio/definition-mapper:2.0.0
    links:
    - nats
    - postgres
    depends_on:
    - config-store
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      NATS_URI: nats://nats:4222
  group-store:
    image: ernestio/group-store:2.0.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      NATS_URI: nats://nats:4222
  logger:
    image: ernestio/logger:2.0.0
    ports:
    - 22001:22001
    volumes:
    - ./logs/:/var/logs/
    - ./config/:/etc/ernest/
    links:
    - nats
    depends_on:
    - config-store
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      ERNEST_LOG_CONFIG: /etc/ernest/
      ERNEST_LOG_FILE: /var/logs/ernest.log
      JWT_SECRET: GENERATEDJWTSECRET
      NATS_URI: nats://nats:4222
  monit:
    image: ernestio/monit:2.0.0
    ports:
    - 22000:22000
    links:
    - nats
    depends_on:
    - config-store
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      JWT_SECRET: GENERATEDJWTSECRET
      NATS_URI: nats://nats:4222
  nats:
    image: nats
    ports:
    - 4222:4222
  nginx:
    image: nginx
    ports:
    - 443:443
    volumes:
    - ./config/nginx/ernest.local:/etc/nginx/conf.d/default.conf
    - ./config/nginx/ernest.key:/etc/nginx/conf.d/ernest.key
    - ./config/nginx/ernest.crt:/etc/nginx/conf.d/ernest.crt
    links:
    - api-gateway:api-gateway
    - monit:monit
    - logger:logger
  postgres:
    image: r3labs/postgres
    volumes:
    - ./postgres/data:/var/lib/postgresql/data
    environment:
      DB_NAME: users,groups,datacenters,services,usage
  scheduler:
    image: ernestio/scheduler:2.0.0
    links:
    - nats
    - postgres
    depends_on:
    - config-store
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      NATS_URI: nats://nats:4222
  service-store:
    image: ernestio/service-store:2.0.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      NATS_URI: nats://nats:4222
  usage-store:
    image: ernestio/usage-store:2.0.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      NATS_URI: nats://nats:4222
  user-store:
    image: ernestio/user-store:2.0.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      NATS_URI: nats://nats:4222
networks: {}
