#!/bin/bash

set -e

command_exists () {
    if ! type "$1" &> /dev/null; then
        echo -e "\nCheck failed! prerequisite requirements not met\n$1 not found! Please make requirement is installed."
        exit 1
    fi
}
echo "#################"
echo "Ernest Setup Tool"
echo "#################"

echo

# Check for prerequisites
echo "Checking Prerequisites"
command_exists wget
command_exists openssl
command_exists docker
command_exists docker-compose

# Setup config (hostname & nginx ssl)
echo
echo "Please enter in the hostname you wish ernest to run as"
read ERNESTHOST

openssl req \
    -new \
    -newkey rsa:4096 \
    -days 365 \
    -nodes \
    -x509 \
    -subj "/C=UK/ST=London/L=London/O=ErnestIO/CN=$ERNESTHOST" \
    -keyout ./config/nginx/ernest.key \
    -out ./config/nginx/ernest.crt

sed -i "s/ERNESTHOST/$ERNESTHOST/g" ./config/nginx/ernest.local

# Setup a random JWT Token for api-gateway
TOKEN=`openssl rand -base64 32`
sed -i "s:GENERATEDJWTSECRET:$TOKEN:g" docker-compose.yml

# Make volume for postgres data
mkdir -p postgres/data


echo
echo "Starting Ernest"
# run docker compose, add a '-d' to run in daemon mode
docker-compose up -d

# Download the natsc tool
wget https://s3-eu-west-1.amazonaws.com/ernest-tools/natsc-`uname` -O natsc
chmod +x ./natsc

# setup admin accounts
./natsc request -s nats://127.0.0.1:4222 -t 5 -r 99 'group.set' '{"id":"1","name": "admin"}'
./natsc request -s nats://127.0.0.1:4222 -t 5 -r 99 'user.set' '{"group_id": 1, "username": "admin", "password": "w4rmR3d", "admin":true}'

echo
echo "Setup complete. Please target ernest using https://127.0.0.1:443, or https://$ERNESTHOST"
