---
version: '2'
services:
  nats:
    image: nats
    ports:
      - 4222:4222
    restart: always
  postgres:
    image: postgres:9.6.5-alpine
    volumes:
      - ./config/postgres:/docker-entrypoint-initdb.d
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      DB_NAME: users,projects,environments,usage,authorizations,policies
    restart: always
  nginx:
    image: nginx:1.13.5-alpine
    volumes:
      - ./config/nginx/ernest.local:/etc/nginx/conf.d/default.conf
      - ./config/nginx/ernest.key:/etc/nginx/conf.d/ernest.key
      - ./config/nginx/ernest.crt:/etc/nginx/conf.d/ernest.crt
    links:
      - api-gateway:api-gateway
      - monit:monit
      - logger:logger
      - notify:notify
    ports:
      - 443:443
    restart: always
