---
version: '2'
services:
  redis:
    image: redis
  nats:
    image: nats
    ports:
      - 4222:4222
  postgres:
    image: r3labs/postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      DB_NAME: users,groups,datacenters,services
  nginx:
    image: nginx
    volumes:
      - ./config/nginx/ernest.local:/etc/nginx/conf.d/default.conf
      - ./config/nginx/ernest.key:/etc/nginx/conf.d/ernest.key
      - ./config/nginx/ernest.crt:/etc/nginx/conf.d/ernest.crt
    links:
      - api-gateway:api-gateway
      - monit:monit
      - logger:logger
    ports:
      - 443:443
