#!/usr/bin/env bash

blue='\033[34;1m'
nc='\033[0m'

printf "\n$blue%s\n%s$nc\n\n" "Ernest Upgrade Tool" "-------------------"

api_gateway=$(docker ps | grep api-gateway | awk '{print $1}')
token=$(docker inspect $api_gateway -f '{{range $v := .Config.Env}}{{println $v}}{{end}}' | grep JWT_SECRET | sed "s/JWT_SECRET=//")
crypto_key=$(docker inspect $api_gateway -f '{{range $v := .Config.Env}}{{println $v}}{{end}}' | grep ERNEST_CRYPTO_KEY | sed "s/ERNEST_CRYPTO_KEY=//")

docker-compose down
git checkout docker-compose.yml
git checkout config/nginx/ernest.local
git checkout master
git pull

export TOKEN=$token CRYPTO_KEY=$crypto_key

printf "\n$blue%s$nc\n" "Starting upgrade"

./setup
