@service @service_import
Feature: Service import

  Scenario: Non logged service import
    Given I setup ernest with target "https://ernest.local"
    And I logout
    When I run ernest with "service import"
    Then The output should contain "You're not allowed to perform this action, please log in"
    When I run ernest with "service import imported"
    Then The output should contain "You're not allowed to perform this action, please log in"

  Scenario: Logged service import errors
    Given I setup ernest with target "https://ernest.local"
    And I'm logged in as "usr" / "pwd"
    When I run ernest with "service import"
    Then The output should contain "You should specify an existing datacenter name"
    When I run ernest with "service import unexisting"
    Then The output should contain "You should specify a valid service name"

  Scenario: Logged service non existing import
    Given I setup ernest with target "https://ernest.local"
    And I'm logged in as "usr" / "pwd"
    And the datacenter "test_dc" does not exist
    And I run ernest with "datacenter create aws --secret_access_key tmp_secret_access_key --access_key_id tmp_secret_up_to_16_chars --region tmp_region --fake test_dc"
    And The service "imported" does not exist
    When I run ernest with "service import test_dc imported"
    Then The output line number "3" should contain "Importing rds instances:"
    And The output line number "4" should contain "- found"
    And The output line number "5" should contain "Engine    : engine"
    And The output line number "6" should contain "Cluster   : cluster"
    And The output line number "7" should contain "Endpoint  : endpoint"
    And The output line number "8" should contain "RDS instances imported"
    And The output line number "9" should contain "Importing rds clusters:"
    And The output line number "10" should contain "- found"
    And The output line number "11" should contain "Engine    : engine"
    And The output line number "12" should contain "Endpoint  : endpoint"
    And The output line number "13" should contain "RDS clusters imported"
    And The output line number "14" should contain "Importing ELBs:"
    And The output line number "15" should contain "- found"
    And The output line number "16" should contain "Status    : done"
    And The output line number "17" should contain "ELBs imported"
    And The output line number "18" should contain "Importing nats:"
    And The output line number "19" should contain "- found"
    And The output line number "20" should contain "Status    : done"
    And The output line number "21" should contain "Nats imported"
    And The output line number "22" should contain "Importing instances:"
    And The output line number "23" should contain "- found"
    And The output line number "24" should contain "IP        :"
    And The output line number "25" should contain "Status    : done"
    And The output line number "26" should contain "Instances successfully imported"
    And The output line number "27" should contain "Importing ebs volumes:"
    And The output line number "28" should contain "- found"
    And The output line number "29" should contain "Status : done"
    And The output line number "30" should contain "EBS volumes successfully imported"
    And The output line number "31" should contain "Importing networks:"
    And The output line number "32" should contain "- found"
    And The output line number "33" should contain "IP     :"
    And The output line number "34" should contain "Status : done"
    And The output line number "35" should contain "Networks successfully imported"
    And The output line number "36" should contain "Importing firewalls:"
    And The output line number "37" should contain "- found"
    And The output line number "38" should contain "Status    : done"
    And The output line number "39" should contain "Firewalls imported"
    And The output line number "40" should contain "Importing s3 buckets:"
    And The output line number "41" should contain "- found"
    And The output line number "42" should contain "ACL       : by grantees"
    And The output line number "43" should contain "Status    :"
    And The output line number "44" should contain "S3 buckets imported"
    And The output line number "45" should contain "SUCCESS: service successfully imported"
